apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: root-catalog-location
  description: "Punto de entrada para el catálogo de OKF en GitHub"
spec:
  type: file
  targets:
    - ./org/domain-cliente-a.yaml
    - ./org/domain-cliente-b.yaml
    - ./systems/system-cliente-a.yaml
    - ./systems/system-cliente-b.yaml
    - ./components/oracle-linux-vm.yaml
    - ./components/apache-tomcat-vm.yaml
    - ./components/wildfly-vm.yaml
