apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: oracle-linux-vm-provision
  title: "Oracle Linux VM Base"
  description: "Servicio base para el aprovisionamiento de máquinas virtuales con Oracle Linux"
spec:
  type: infrastructure
  lifecycle: production
  owner: guest
  # Este servicio base lo asociaremos temporalmente al Sistema del Cliente A para ilustrar el ejemplo
  system: cliente-a-infra-system
