apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wildfly-oracle-vm
  title: "WildFly App Server"
  description: "Servidor de aplicaciones WildFly ejecutándose sobre Oracle Linux"
spec:
  type: service
  lifecycle: experimental
  owner: guest
  system: cliente-a-infra-system
  dependsOn:
    - component:oracle-linux-vm-provision
