apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: cliente-b-infra-system
  title: "Infraestructura Cliente B"
  description: "Agrupación de servicios de cómputo y middleware para el Cliente B"
spec:
  owner: guest
  domain: cliente-b
